export const information =[
    {
        id:1,
        src: `${process.env.PUBLIC_URL}/Images/apple.jpg`, alt: 'Image 1',
        title:'Workout Plans',
        description:"Whether you're looking to build strength, improve flexibility, or enhance your overall fitness, we've got you covered. Our expertly designed workout routines include:",
        bold1:'Leg Workouts:',
        para1:'Sculpt and strengthen your legs with exercises that target your quads, hamstrings, calves, and glutes.',
        bold2:'Arm Workouts: ',
        para2:'Tone and build muscle in your biceps, triceps, and shoulders with our targeted arm routines.',
        bold3:'Hand Workouts:',
        para3:' Improve your grip strength and dexterity with our specialized hand exercises.',
    },
    {
        id:2,
        src: `${process.env.PUBLIC_URL}/Images/orange.jpg`, alt: 'Image 2',
        title:'Personalized Nutrition Plans',
        description:"Nutrition is a key component of any fitness journey. Our certified nutritionists provide tailored meal plans that suit your specific goals, whether it's weight loss, muscle gain, or maintaining a healthy lifestyle. We offer:",
        bold1:'Customized diet plans:',
        para1:"Our certified nutritionists create diet plans tailored to your specific needs, whether you're aiming for weight loss, muscle gain, or maintaining a healthy lifestyle. We take into account your dietary preferences, allergies, and nutritional requirements to ensure you get the best results",
        bold2:'Healthy recipes: ',
        para2:' Enjoy a variety of delicious and nutritious recipes that are easy to prepare. Our meal suggestions are designed to keep you energized and satisfied while meeting your dietary goals.',
        bold3:'Nutritional tips and advice:',
        para3:'Stay informed with our expert advice on nutrition. We provide practical tips on healthy eating habits, portion control, and how to make smart food choices.',
    },
    {
        id:3,
        title:' Mindfulness and Meditation',
        src: `${process.env.PUBLIC_URL}/Images/grapes.jpg`, alt: 'Image 3',
        description:"A healthy mind is just as important as a healthy body. Our meditation and mindfulness sessions are designed to help you reduce stress, increase focus, and improve your overall mental well-being. Join our guided meditation sessions and discover the benefits of mindfulness.",
        bold1:'Guided Meditation Sessions:',
        para1:'Our experienced instructors lead you through guided meditation practices that help reduce stress, improve concentration, and enhance emotional well-being. These sessions are suitable for all levels, from beginners to advanced practitioners.',
        bold2:'Mindfulness Practices: ',
        para2:'Learn techniques to cultivate mindfulness in your daily life. We offer exercises and practices that help you stay present, manage anxiety, and improve your mental clarity.',
        bold3:'Stress Reduction',
        para3:'Discover methods to manage and reduce stress through meditation and mindfulness. Our resources are designed to help you relax, unwind, and maintain a positive outlook.',
    },
    {
        id:3,
        title:' Community Interaction',
        src: `${process.env.PUBLIC_URL}/Images/banana.jpg`, alt: 'Image 4',
        bold1:'Free User Chats:',
        para1:' Engage in real-time conversations with other fitness enthusiasts. Share tips, motivate each other, and celebrate your progress together.',
        bold2:'Forums and Discussion Boards: ',
        para2:'Participate in discussions on various fitness topics, ask questions, and get answers from experts and peers.',
        bold3:'Group Challenges and Events:',
        para3:'Join our community challenges and events to stay motivated and push your limits.',
    },
]